version: '3.9'

services:

  spider:
    build:
      context: .
      args:
        options: --reload
      dockerfile: Dockerfile
    image: spider
    container_name: spider
    restart: always
    volumes:
      - ./:/app
    command: gunicorn spider.wsgi:application -b 0.0.0.0:8000 --reload
#    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"
