version: '3.9'

services:

  spider:
    build:
      context: .
      dockerfile: Dockerfile
    image: spider
    container_name: spider
    environment:
      - APP_NAME=${APP_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - EXTERNAL_TOOLS_DIR=${EXTERNAL_TOOLS_DIR}
    volumes:
      - ./:/app
    command: daphne -b 0.0.0.0 -p 8000 spider.asgi:application
    ports:
      - "8001:8000"
      - "8282:8282"
    restart: always
