version: '3.9'

services:

  spider:
    build:
      context: .
      dockerfile: Dockerfile
    image: spider
    container_name: spider
    command: gunicorn spider.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: "always"
