version: '3.9'

services:

  spideros:
    build:
      context: .
      dockerfile: Dockerfile
    image: spideros
    container_name: spideros
    command: gunicorn spider.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: "always"
