version: '3.9'

services:
  spider:
    build:
      context: .
      dockerfile: .docker/ubuntu.Dockerfile
    image: anyxel/spider:latest
    container_name: spider
    #    environment:
    #      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./:/app
    ports:
      - "8001:8000"
      - "8282:8282"
    restart: always
