version: '3.9'

services:

  spider:
    build:
      context: .
      dockerfile: Dockerfile
    image: spider
    container_name: spider
    restart: always
    volumes:
      - ./:/app
    command: daphne -b 0.0.0.0 -p 8000 spider.asgi:application
    ports:
      - "8001:8000"
    networks:
      - anyxel

# networks
networks:
  anyxel:
    driver: bridge
