version: '3.9'

services:
  spider:
    build:
      context: .
      dockerfile: .docker/prod/ubuntu.Dockerfile
    image: anyxel/spider:beta
    container_name: spider
    volumes:
      - ./:/app
    ports:
      - "8001:8000"
      - "8282:8282"
    restart: always
