# Generated by Django 5.0.1 on 2024-01-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lang', models.CharField(max_length=10)),
                ('url', models.TextField()),
                ('branch', models.CharField(max_length=100)),
                ('folder', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
                ('has_dependencies', models.BooleanField(default=False)),
            ],
        ),
    ]
