# Generated by Django 5.0.1 on 2024-01-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lang', models.CharField(max_length=10)),
                ('url', models.TextField()),
                ('folder', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=100)),
                ('has_dependencies', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
